---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-poller-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-poller-serviceaccount
roleRef:
  kind: Role
  name: {{ .Release.Name }}-poller-role
  apiGroup: rbac.authorization.k8s.io