---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-notifier-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-notifier-serviceaccount
roleRef:
  kind: Role
  name: {{ .Release.Name }}-notifier-role
  apiGroup: rbac.authorization.k8s.io