---
- name: "Setup RDS instance, k8s cluster and VPC peering"
  hosts: localhost
  gather_facts: no
  roles:
  - ../roles/k8s_setup
  - ../roles/metrics_setup
  - ../roles/k8s_autoscaling
  - ../roles/rds_setup
  - ../roles/peering_setup
