---
apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
    name: {{ .Release.Name }}-ingress
    annotations: 
        kubernetes.io/ingress.class: "nginx"
        ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.host }}
  rules:
  - host: {{ .Values.ingress.host }}
    http: 
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-svc
          servicePort: 8080
