---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-webapp-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-webapp-serviceaccount
roleRef:
  kind: Role
  name: {{ .Release.Name }}-webapp-role
  apiGroup: rbac.authorization.k8s.io