---
- name: Include default variables
  include_vars:
    file: ../../../vars/main.yml

- name: Install latest version of "openjdk-8-jdk" 
  apt:
    name: openjdk-8-jdk
    state: latest
    install_recommends: yes
    update_cache: yes
  become: yes

- name: Ensure Java is installed.
  package:
    name: openjdk-8-jdk
    state: present
  become: yes

- name: Add Jenkins apt-key
  apt_key: 
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key 
    state: present    
  become: yes

- name: Add Jenkins apt repository
  apt_repository: 
    repo: 'deb https://pkg.jenkins.io/debian-stable binary/' 
    state: present
  become: yes

- name: Install jenkins
  apt: 
    name: jenkins
    state: present
    update_cache: yes
    install_recommends: yes
  become: yes

- name: Install nginx
  apt: 
    name: nginx
    state: present
    install_recommends: yes   
  become: yes 

- name: Add certbot apt repository
  apt_repository: 
    repo: 'ppa:certbot/certbot'
    state: present
  become: yes

- name: Install certbot
  apt: 
    name: python-certbot-nginx
    state: present
    install_recommends: yes
  become: yes

- name: Remove the default nginx config
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent
  become: yes

- name: Copy the config file to required location
  template:
    src: nginx.config.j2
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Test Nginx
  shell: nginx -t
  become: yes

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded
  become: yes

- name: Use Certbot to generate certificates
  shell: certbot --nginx -n -d "{{ sub_domain }}" --email "{{ email }}" --agree-tos --redirect
  become: yes

- name: Ensure repository key is installed for docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Ensure Docker Registry is available
  apt_repository: repo='deb https://download.docker.com/linux/ubuntu bionic stable' state=present
  become: yes

- name: Ensure Docker and Dependencies are installed
  apt: name=docker-ce update_cache=yes
  become: yes

- name: To provide necessary permissions to communicate to docker socket
  file:
    dest: /var/run/docker.sock
    owner: root
    group: root
    mode: 0666
  become: yes

- name: Install kubectl
  shell: |
    apt-get update && apt-get install -y apt-transport-https 
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
    echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
    apt-get update
    apt-get install -y kubectl
  become: yes

- name: Install kops
  shell: |
    wget -O kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
    chmod +x ./kops
    mv ./kops /usr/local/bin/ 
  become: yes

- name: Install helm
  shell : snap install helm --classic
  become: yes