spring:
  datasource:
    url: jdbc:mysql://mysql3:3306/csye7125_notifier?serverTimezone=UTC
    username: root
    password: 11223344
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "*"
server:
  servlet:
    context-path:
