---
- name: Delete Cluster
  shell: az aks delete --name "{{name}}" --resource-group "{{ resource_group }}" 

- name: Delete Virtual Network
  shell: az network vnet delete --resource-group "{{ resource_group }}" --name "{{name}}-vnet"