---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: zookeeper
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: client
  selector:
    app: zookeeper
